### ISSUE TITLE
Update Options Links to point to new Settings page

### ISSUE THREAD

**Issue by bobbyg603** [BugSplat-Git/bugsplat-docs#106]
- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/administration/account-managment/deleting-databases.md
  3,136: If you're looking to remove a database for any reason, you can do so via the Database section of the [Options](https://app.bugsplat.com/v2/options) page.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/administration/account-managment/how-to-migrate-databases-between-users-and-accounts.md
  3,201: Databases are owned by companies. To transfer ownership of a database to another company, use the ‘Transfer Database Ownership’ option on the Database section of the [Options](https://app.bugsplat.com/v2/options) page.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/changelog/changelog.md
  1047,162: * Symbols for Electron applications can now be automatically resolved. Select the new Include Electron Symbols checkbox on our [Options](https://app.bugsplat.com/v2/options) page to enable this feature.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/development/integrating-with-tools/issue-trackers/assembla.md
  10,115: 4. Login to your BugSplat account and navigate to the Defect Tracker tab of the [Options](https://app.bugsplat.com/v2/options?tab=defect) page

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/development/integrating-with-tools/issue-trackers/azure-devops.md
  8,49: 2. Go to the ‘[Options](https://app.bugsplat.com/v2/options)’ page and under ‘Defect Tracking System Setup’ select Azure DevOps from the drop-down menu.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/development/integrating-with-tools/issue-trackers/fogbugz.md
  8,50: 2. Go to the [‘Options’](https://app.bugsplat.com/v2/options) page and under ‘Defect Tracking System Setup’ select FogBugz from the drop-down menu.
  9,134: 3. Enter your Fogbugz, Username, and your Fogbugz URL into the appropriate boxes on the BugSplat [‘Options’](https://app.bugsplat.com/v2/options) page.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/development/integrating-with-tools/issue-trackers/github-issues.md
  8,48: 2. Go to the [Options](https://app.bugsplat.com/v2/options) page and under the **Defect Tracker** tab select **GitHub Issues** from the drop-down menu.
  9,142: 3. Enter your GitHub **Username**, **API Token** and Repo Owner into the appropriate boxes on the BugSplat [Options](https://app.bugsplat.com/v2/options) page.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/development/integrating-with-tools/issue-trackers/jira.md
  8,49: 2. Go to the ‘[Options](https://app.bugsplat.com/v2/options)’ page and under ‘Defect Tracking System Setup’ select Jira from the drop-down menu.
  9,132: 3. Enter your Username, Password, URL, and IssueType into the appropriate boxes on the BugSplat ‘[Options](https://app.bugsplat.com/v2/options)’ page.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/development/integrating-with-tools/issue-trackers/youtrack.md
  8,50: 2. Go to the [‘Options’](https://app.bugsplat.com/v2/options) page and under ‘Defect Tracking System Setup’ select YouTrack from the drop-down menu.
  9,172: 3. Enter your Username, YouTrack API Token, YouTrack URL, and any of the additional options into the appropriate boxes on the BugSplat [‘Options’](https://app.bugsplat.com/v2/options) page.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/development/integrating-with-tools/messanger-apps/discord.md
  10,54: 2. Navigate to the [Options](https://app.bugsplat.com/v2/options) page

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/development/integrating-with-tools/messanger-apps/email.md
  10,49: 2. Go to the ‘[Options](https://app.bugsplat.com/v2/options)’ page and hit the button under ‘Email Alerts’

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/development/integrating-with-tools/messanger-apps/microsoft-teams.md
  10,54: 2. Navigate to the [Options](https://app.bugsplat.com/v2/options) page

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/development/integrating-with-tools/messanger-apps/slack.md
  10,54: 2. Navigate to the [Options](https://app.bugsplat.com/v2/options) page.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/development/web-services/oauth2.md
  9,171: To authenticate via OAuth2 client credentials you will need to create a Client Id and Client Secret pair on the Integrations tab on the [Options](https://app.bugsplat.com/v2/options?tab=integrations) page.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/troubleshooting.md
  23,475: ⟪ 274 characters skipped ⟫they are incoming at a rate greater than 1,000,000 per month. Additionally, BugSplat can reject repeated crashes coming from the same IP address via a setting on the [Options](https://app.bugsplat.com/v2/options?tab=misc) page. A list of rejected crashes can be found on BugSplat's [Errors](https://app.bugsplat.com/v2/errors) page.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/game-development/unreal-engine.md
  79,208: If you'd like to forward crashes to the original `DataRouterUrl` specified in `DefaultEngine.ini` you can enable the **Forward Crashes** option under the Privacy tab on the [Options](https://app.bugsplat.com/v2/options?tab=privacy) page. Forwarding crash reports to Epic is useful when a crash in your game is caused by the underlying engine and you are working with Epic Games to resolve the issue. If the Forward to Epic option is enabled, an Epic Correlation-ID will be added to the description of all Unreal Engine crashes that were successfully forwarded to Epic.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/updates/changelog.md
  1205,162: * Symbols for Electron applications can now be automatically resolved. Select the new Include Electron Symbols checkbox on our [Options](https://app.bugsplat.com/v2/options) page to enable this feature.

**Comment by splatyourbugs** [comment]
Done!
