### ISSUE TITLE
Update Company Links to point to new Settings page

### ISSUE THREAD

**Issue by bobbyg603** [BugSplat-Git/bugsplat-docs#107]
- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/administration/account-managment/how-to-migrate-databases-between-users-and-accounts.md
  7,388: Note: You must be a user on databases owned by both companies for this to work. If you do not see the company for which you want to transfer ownership, then you are likely not a user on a database owned by that company. Getting access to a database owned by the desired company will fix this problem. You can view a list of a company's databases on the [Company](https://app.bugsplat.com/v2/company) page.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/administration/billing/billing-and-plan-managment/add-or-update-billing-address-for-bugsplat-accounts.md
  5,61: To do so, navigate to the [Company](https://app.bugsplat.com/v2/company) page and click on the link that says 'Manage your plan.'

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/administration/billing/billing-and-plan-managment/adding-billing-address-for-vat-purposes.md
  5,61: To do so, navigate to the [Company](https://app.bugsplat.com/v2/company) page and click on the link that says 'Manage your plan.'

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/administration/billing/billing-and-plan-managment/updating-credit-card-associated-with-account.md
  3,134: Upgrading the credit card associated with your BugSplat account is easy. To do so, navigate to the [Company](https://app.bugsplat.com/v2/company) page and click on the link that says 'Manage your plan.'

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/administration/billing/billing-and-plan-managment/updating-email-address-for-receipts-and-invocies.md
  5,61: To do so, navigate to the [Company](https://app.bugsplat.com/v2/company) page and click on the link that says 'Manage your plan.'

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/administration/billing/billing-and-plan-managment/viewing-billing-history-and-past-invoices.md
  5,61: To do so, navigate to the [Company](https://app.bugsplat.com/v2/company) page and click on the link that says 'Manage your plan.'

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/administration/billing/upgrades/annual-plan-upgrades.md
  7,65: You can see your usage on the [Company](https://app.bugsplat.com/v2/company) page. If anything is in 'red' then it means that you're over your limit.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/administration/billing/upgrades/monthly-upgrade-policy.md
  11,65: You can see your usage on the [Company](https://app.bugsplat.com/v2/company) page. If anything is in 'red' then it means that you're over your limit.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/administration/paid-plans-and-upgrades/upgrade-policy.md
  5,65: You can see your usage on the [Company](https://app.bugsplat.com/v2/company) page. If anything is in 'red' then it means that you're over your limit.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/adding-uses-to-your-account.md
  7,113: To add a team member to all your company's databases, simply add them via the [Company](https://app.bugsplat.com/v2/company) page. They will receive an email providing a prompt about setting up their account.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/create-a-new-database-in-bugsplat.md
  17,83: Alternatively, a database can be created on the [Company](https://app.bugsplat.com/v2/company) page by clicking the button labeled `+ Create Database`.  This method is also useful when wishing to set up multiple databases under an account.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/cross-platform/breakpad.md
  21,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application
  97,98: The BugSplat database for your crash reports is created on the [Company](https://app.bugsplat.com/v2/company) page. Typically you will create a new database for each major release of your product.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/cross-platform/deno.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/cross-platform/dot-net-standard.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/cross-platform/electron.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/cross-platform/java.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/cross-platform/node.js.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/cross-platform/python.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/cross-platform/qt.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/cross-platform/crashpad/README.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application
  158,98: The BugSplat database for your crash reports is created on the [Company](https://app.bugsplat.com/v2/company) page. Typically you will create a new database for each major release of your product.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/desktop/linux.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/desktop/macos.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/desktop/windows-dot-net-framework.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application
  32,80:    * The BugSplat database is created on the [Company](https://app.bugsplat.com/v2/company) page. Typically, you will create a new database for each major release of your product.

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/desktop/cplusplus/README.md
  15,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/game-development/cryengine.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/game-development/unity.md
  11,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/game-development/unreal-engine.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/mobile/android.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/mobile/ionic.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/web/javascript.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/web/react.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/integrations/web/vue.md
  9,51: * Create a new [database](https://app.bugsplat.com/v2/company) for your application

- [x] Users/bobby/Desktop/bugsplat/bugsplat-docs/introduction/getting-started/posting-a-test-crash/myjavacrasher.md
  38,90: * The BugSplat database is created and selected on the [Company](https://app.bugsplat.com/v2/company) page.

**Comment by splatyourbugs** [comment]
Done and shipped!  @bobbyg603 lets goooooo!!! Woo!

**Comment by bobbyg603** [comment]
thanks @splatyourbugs !!! huge help 🙂
