### ISSUE TITLE
Move these docs to a new folder for legacy pricing 

### ISSUE THREAD

**Issue by splatyourbugs** [BugSplat-Git/bugsplat-docs#108]
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/free-trial-and-new-accounts/free-trial
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/free-trial-and-new-accounts/choosing-a-plan
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/free-trial-and-new-accounts/full-monthly-pricing-sheet
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/upgrades
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/upgrades/monthly-upgrade-policy
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/upgrades/enterprise-plans
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/upgrades/annual-plan-upgrades
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/billing-and-plan-managment/viewing-billing-history-and-past-invoices
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/billing-and-plan-managment/add-or-update-billing-address-for-bugsplat-accounts
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/billing-and-plan-managment/adding-billing-address-for-vat-purposes
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/billing-and-plan-managment/updating-email-address-for-receipts-and-invocies
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/billing-and-plan-managment/updating-credit-card-associated-with-account
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/free-plans-from-bugsplat/standard-free-plan
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/free-plans-from-bugsplat/free-accounts-for-indie-game-development
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/free-plans-from-bugsplat/bugsplat-free-accounts-for-students-and-teachers
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/free-plans-from-bugsplat/bugsplat-free-accounts-for-not-for-profit-open-source-projects
- [ ] https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/administration/billing/free-plans-from-bugsplat/good-causes

**Comment by bobbyg603** [comment]
@splatyourbugs is this done?

**Comment by bobbyg603** [comment]
I think it's safe to close this.
