### ISSUE TITLE
Review Crash Reporter Doc for Errors

### ISSUE THREAD

**Issue by splatyourbugs** [BugSplat-Git/bugsplat-docs#121]
Turns out we’re the top google hit for the term ‘Crash Reporter’!  The only problem is that our link directs to a pretty lame post in our docs.  I’ve pushed up the document to represent our business better.  

Mind reviewing and proposing any changes? https://app.gitbook.com/o/-LBMgmIbZKqjzfg08G3A/s/-LBMgmIcgkIXSUfnXDSv/education/faq/what-is-a-crash-reporter

It's live now so maybe a new branch should be created if you see any errors?

**Comment by bobbyg603** [comment]
Seems fine
